name: upload-assets
base: core18
version: '0.3.0'
summary: A command-line tool for managing the assets server
description: |
  This is intended to be a simple command-line tool for uploading assets 
  to an https://assets.ubuntu.com-like assets server.

grade: stable
confinement: strict

parts:
  repo:
    plugin: python
    source: .

apps:
  upload-assets:
    command: upload-assets
    plugs:
      - home
      - network-bind
