name: Tests

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update && sudo apt install -y --no-install-recommends python3-setuptools
          pip3 install twine wheel

      - name: Build package
        run: python3 setup.py sdist bdist_wheel

      - name: Twine check
        run: python3 -m twine check dist/*
        
  check-inclusive-naming:
    name: Check inclusive naming
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check inclusive naming
        uses: canonical-web-and-design/inclusive-naming@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail-on-error: true
